name: Tag tester

on:
  workflow_call:

jobs:
  tag_printer:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.outputversion.outputs.version_tag }}
    steps:

    - name: Check out source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Calculate tag
      id: version
      uses: paulhatch/semantic-version@v5.0.3
      with:
        major_pattern: '/^(major|breaking|break)!?(\(.*\))?!?:\s.+$|((^(\w+)!(\(.*\))?!?:\s.+$)|(^(\w+)(\(.*\))!:\s.+$))/'
        minor_pattern: '/^(feat|feature)(\(.*\))?:\s.+$/'

    - name: Update Pull Request
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `Predicted tag change: ${{ steps.version.outputs.previous_version }} -> ${{ steps.version.outputs.version_tag }}`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: output tag version to next jobs
      id: outputversion
      run: |
        echo "version_tag=${{ steps.version.outputs.version_tag }}" >> $GITHUB_OUTPUT

  release_checker:
    needs: tag_printer
    name: sjekker version
    secrets: inherit
    uses: Mattilsynet/wf-map-release-check/.github/workflows/Updatecheck.yaml@v1.0.16
    with:
      send_to_pr: true
      self_predicted_tag: "${{ needs.tag_printer.outputs.version_tag }}"
      
